algoritmo "candidatos"
// Função : LOPAL (Lógica de programação)

// Autor :Caline Myrella e Lorena Oliveira
// Data : 14/04/2026
// Seção de Declarações 
var
//Declaração de variaveis

idade:real
java,python:literal

inicio
// Seção de Comandos 

   escreva ("digite sua idade: ")
   leia(idade)
   
   escreva ("Você tem conhecimento sobre o JavaScript?")
   leia(java)
   
   escreva ("Você tem conhecimento sobre o Python?")
   leia(python)

   se (idade >=18) e ((java="s") ou (python="s")) entao
   
   escreval ("Foi Aprovado")
   
            senao
            escreval ("Foi Recusado")
   fimse
   

fimalgoritmo
