algoritmo "entrada gratuita ingresso"
// Função :LOPAL(Lógica de ´programação)

// Autor :Caline e Lorena
// Data : 14/04/2026
// Seção de Declarações 
var
 //Declaração de variaveis
 
 idade:real
inicio
// Seção de Comandos

  escreva ("digite sua idade: ")
  leia(idade)
  
  se (idade < 5) ou (idade >=65) entao
  
  escreval ("entrada gratuita")
  senao
  escreval ("pagar o ingresso")
  fimse

 
fimalgoritmo
