algoritmo "Nota"
// Disciplina : Lopal(Lógica de Programação)

//F9(executar código)

// Autor :Lorena Oliveira e Caline Myrella
// Data : 14/04/2026

var
// Declaraçã de Variavéis
nota,frequencia:real

inicio
// Seção de Comandos
   escreva("digite a nota do aluno:" )
   leia(nota)
   
   escreva("digite a frequência do aluno:" )
   leia(frequencia)

   se (nota>=7) e (frequencia>=75) entao
   
   escreval("o aluno foi aprovado")
   
   
   senao
   escreval("o aluno foi reprovado")
   fimse
   

fimalgoritmo
